const DURATION_FILM__FOR_FILTER = 40;
const REG_EXP_NAME = /^[a-zA-Zа-яА-Я\sё-]+$/;
const REG_EXP_EMAIL = /^[-!#$%&'*+\\/0-9=?A-Z^_a-z`{|}~](\.?[-!#$%&'*+\\/0-9=?A-Z^_a-z`{|}~])*@[a-zA-Z0-9](-*\.?[a-zA-Z0-9])*\.[a-zA-Z](-?[a-zA-Z0-9])+$/;

const MAX_WIDTH_FOR_MOBILE = 480;
const MIN_WIDTH_FOR_DESKTOP = 1280;
const COUNT_INITIAL_MOVIES_ON_SCREEN_FOR_MOBILE = 2;
const COUNT_ADDED_MOVIES_ONCLICK_FOR_MOBILE = 5;
const COUNT_ADDED_MOVIES_ONCLICK_FOR_DESKTOP = 3;
const COUNT_INITIAL_MOVIES_ON_SCREEN_FOR_DESKTOP = 12;
const COUNT_INITIAL_MOVIES_ON_SCREEN_FOR_PAD = 8;

export {
  DURATION_FILM__FOR_FILTER,
  REG_EXP_NAME,
  REG_EXP_EMAIL,
  MAX_WIDTH_FOR_MOBILE,
  COUNT_INITIAL_MOVIES_ON_SCREEN_FOR_MOBILE,
  COUNT_ADDED_MOVIES_ONCLICK_FOR_MOBILE,
  MIN_WIDTH_FOR_DESKTOP,
  COUNT_ADDED_MOVIES_ONCLICK_FOR_DESKTOP,
  COUNT_INITIAL_MOVIES_ON_SCREEN_FOR_DESKTOP,
  COUNT_INITIAL_MOVIES_ON_SCREEN_FOR_PAD,
};